# Generated by Django 5.1.5 on 2025-02-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('patron', 'Patron'), ('librarian', 'Librarian')], max_length=10, null=True),
        ),
    ]
