# Generated by Django 5.1.5 on 2025-04-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_guest',
        ),
    ]
