# Generated by Django 5.1.5 on 2025-03-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
