# Generated by Django 5.1.5 on 2025-04-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
