# Generated by Django 5.1.5 on 2025-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_collectionaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
