# Generated by Django 5.1.5 on 2025-04-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_borrowrequest_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='identifier',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('repair', 'Being Repaired'), ('lost', 'Lost')], default='available', max_length=20),
        ),
    ]
