# Generated by Django 5.1.5 on 2025-04-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_item_identifier_item_author_alter_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
