# Generated by Django 5.1.5 on 2025-04-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('repair', 'Being Repaired'), ('lost', 'Lost')], default='available', max_length=20),
        ),
    ]
