# Generated by Django 5.1.5 on 2025-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("checked_out", "Checked Out"),
                    ("repair", "Being Repaired"),
                    ("lost", "Lost"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
